
[project]
name = "translink"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.136.3",
    "gtfs-realtime-bindings>=2.0.0",
    "httpx>=0.28.1",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.48.0",
]


[tool.setuptools.package-dir]
"" = "."
